# -*- coding: utf-8 -*-
"""filesystem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xp6877YzZJ2Ot8G_vJYHRqu6QRYpK058
"""

import os

def get_image_paths(directory, extensions=['.jpg', '.jpeg', '.png']):
    """
    Returns a list of image file paths in the specified directory and its subdirectories, 
    filtered by the provided file extensions.
    Args:
        directory (str): The path to the directory to search for image files.
        extensions (list, optional): A list of file extensions to include in the search.
            Default is ['.jpg', '.jpeg', '.png'].
    Returns:
        list: A list of image file paths found in the specified directory and its subdirectories.
    Example:
        >>> image_paths = get_image_paths('/images/')
        >>> print(image_paths)
        ['/images/image1.jpg', '/images/subdir/image2.jpeg', '/images/subdir/image3.png']
    """

    image_paths = []
    for dir_path, subdir_names, file_names in os.walk(directory):
        for file_name in file_names:
            if any([file_name.lower().endswith(ext) for ext in extensions]):
                image_paths.append(os.path.join(dir_path, file_name))
    return image_paths