# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XlFyZSGeBgQHWah-SSu1mrPfEd1gzBtJ
"""

import cv2

def blob2image(blob, size):
    blob_image = blob[0].transpose(1, 2, 0)
    blob_image = cv2.resize(blob_image, size)
    # Normalize the pixel values (0-255)
    blob_image = cv2.normalize(blob_image, None, 0, 255, cv2.NORM_MINMAX, cv2.CV_8U)
    return blob_image

def resize(image, width):
    scaling_factor = width / image.shape[1]
    new_height = int(image.shape[0] * scaling_factor)
    return cv2.resize(image, (width, new_height), interpolation=cv2.INTER_AREA)
